env:
  browser: true
  es6: true
extends:
  - standard
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 11
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  "no-unused-vars": "warn"
  "prefer-const": "warn"
  "capitalized-comments": "warn"
  "eqeqeq": "error"
  "no-useless-return": "warn"
